# Generated by Django 2.0.5 on 2018-05-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
        ('core', '0003_pontoturistico_comentario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pontoturistico',
            old_name='comentario',
            new_name='comentarios',
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='avaliacoes',
            field=models.ManyToManyField(to='avaliacoes.Avaliacao'),
        ),
    ]
